# Generated by Django 5.1.6 on 2025-03-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='uid',
            field=models.CharField(default='prompt', max_length=50),
            preserve_default=False,
        ),
    ]
