# Generated by Django 5.1.6 on 2025-03-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_driver_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='license_photos/'),
        ),
    ]
